name: event filters Workflow
 
on:
  push:
    branches:
      - master
      - develop
    tags-ignore:
      - "v*"   # ignores pushes with tags starting with v
  

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Print build
       run: echo 'build'

 test:
   runs-on: windows-latest
   steps:
     - name: Print test - chrome
       run: echo 'test chrome'
     - name: Print test - edge
       run: echo 'test edge'

 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Print deploy
       run: echo 'deploy'
 
