name: Matrix Context


on:
 workflow_dispatch
jobs:
 build:
  runs-on: ubuntu-latest
  strategy:
   matrix:
     os: [ubuntu-latest, windows-latest, macos-latest]
     node: [18.x, 20.x]
  steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node}}"
        check-latest: true
    - name: Verify Node version
      run: node -v
   
       
