name: matrix context
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:   [ubuntu-latest, windows-latest]
        node: [18, 20]
    steps:
      - uses: actions/setup-node@v4
        with: 
         node-version: ${{ matrix.node }} 
      - run: node -v
      - name: Tag summary
        run: echo "OS=${{ matrix.os }}, NODE=${{ matrix.node }}" >> $GITHUB_STEP_SUMMARY
