name: Schedule Workflow

on:
 schedule:
  - cron: "*/5 * * * *"
 workflow_dispatch:

jobs:
 say-hello:
   runs-on: ubuntu-latest
   steps:
     - name: Hello
       run: echo "hello from schedule"
 test:
   runs-on: windows-latest
   steps:
     - name: Print test - chrome
       run: echo "test chrome"
     - name: Print test - edge
       run: echo "test edge"

 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Deploy step
       run: echo "deploying"
 
