name: secrets context
on: [workflow_dispatch]
jobs:
  repo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use repo secret safely
        env:
          TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          echo "Token length: ${#TOKEN}"
  env-secret:
    runs-on: ubuntu-latest
    environment: prod   # exposes environment secrets
    steps:
      - name: Use environment secret safely
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "API key present? $([ -n \"$API_KEY\" ] && echo yes || echo no)"
